### PR TITLE
Added Brazilian Portuguese as an additional language.

### PR DESCRIPTION
**Pull request by alcemirsantos**
First, I translated the labels in the language properties file. Then, I wrote some code also use the Portuguese language.

### CODE REVIEW

**Comment by GSeibt** [comment]
I was referring to commit 3477a4d. The other changes seem fine, though I would suggest storing the new Locale somewhere in a public static field. In Constants for example. Also Locale.forLanguageTag(<tag>) is the modern way of creating a Locale as I understand it. The method will ensure that you are creating a valid language tag.

**Comment by feigensp** [comment]
I took a look and I agree with Georg.

**Comment by alcemirsantos** [comment]
c3b57a1:  in this commit,  I tried to remove the _.classpath_ and the _.project_ files with a `git rebase --onto`. I am not sure if it worked out. 

9b9deed: in this commit, I moved the instances of the new `Locale` to the `Constants.java`

**Comment by GSeibt** [comment]
See #33 . I fixed your branch and added one commit. If you are happy with the changes I will merge them into master. I can help you fix your branch if you need it. I sent you an Email.

**Pull request closed without merging**
